/**
 * user-event.js
 * 
 * @author yuki
 */



export default {
    
    // 必ず USER_XXX の値を取ること
    
    TO_SELECT_SCENE    : 'USER_TO_SELECT_SCENE',
    TO_BATTLE_SCENE    : 'USER_TO_BATTLE_SCENE',
    TO_SKILL_SCENE     : 'USER_TO_SKILL_SCENE',
    TO_CHANGE_SCENE    : 'USER_TO_CHANGE_SCENE',
    TO_CONFIRM_SCENE   : 'USER_TO_CONFIRM_SCENE',
    
    CONFIRM_OK         : 'USER_CONFIRM_OK',
    CONFIRM_CANCEL     : 'USER_CONFIRM_CANCEL',
    
    SELECT_POKEMON     : 'USER_SELECT_POKEMON',
    UNSELECT_POKEMON   : 'USER_UNSELECT_POKEMON',
    
    START_BATTLE       : 'USER_START_BATTLE',
    
    SELECT_SKILL       : 'USER_SELECT_SKILL',
    SELECT_CHANGE      : 'USER_SELECT_CHANGE',
    SELECT_RESIGN_CHECK: 'USER_SELECT_RESIGN_CHECK',
    SELECT_RESIGN_OK   : 'USER_SELECT_RESIGN_OK',
    
};
